/*
 * Copyright (C) 2006-2014 F. Gerbig (fgerbig@users.sourceforge.net)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package jgamebase.gui;

import jgamebase.db.Db;
import jgamebase.db.model.Game;

/**
 * The GameBase GUI.
 * 
 * @author F. Gerbig (fgerbig@users.sourceforge.net)
 */
public class ClearGameLinkDialog extends javax.swing.JDialog {

  /**
	 * 
	 */
  private static final long serialVersionUID = -7723623461226397832L;

  Game game;

  Game linkGame;

  public ClearGameLinkDialog(final Game game) {
    this.game = game;

    initComponents();

    prequel.setEnabled(game.hasPrequel());
    sequel.setEnabled(game.hasSequel());
    related.setEnabled(game.hasRelated());

    if (prequel.isEnabled()) {
      prequel.setSelected(true);
    } else if (sequel.isEnabled()) {
      sequel.setSelected(true);
    } else {
      related.setSelected(true);
    }

    linkTypeChanged();

    this.setSize(320, 160);
    setLocationRelativeTo(null);
    setVisible(true);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox bidirectionalLink;
  private javax.swing.JRadioButton prequel;
  private javax.swing.JRadioButton related;
  private javax.swing.JRadioButton sequel;

  // End of variables declaration//GEN-END:variables

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code
  // <editor-fold defaultstate="collapsed" desc=" Generated Code
  // <editor-fold defaultstate="collapsed"
  // <editor-fold defaultstate="collapsed"
  // desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    final javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
    final javax.swing.JPanel emulatorsPanel = new javax.swing.JPanel();
    final javax.swing.JPanel mainPanel = new javax.swing.JPanel();
    prequel = new javax.swing.JRadioButton();
    sequel = new javax.swing.JRadioButton();
    related = new javax.swing.JRadioButton();
    final javax.swing.JPanel OkCancelPanel = new javax.swing.JPanel();
    final javax.swing.JPanel jPanel9 = new javax.swing.JPanel();
    final javax.swing.JButton okButton = new javax.swing.JButton();
    final javax.swing.JButton cancelButton = new javax.swing.JButton();
    bidirectionalLink = new javax.swing.JCheckBox();

    setTitle("Clear Game Link");
    setModal(true);
    addWindowListener(new java.awt.event.WindowAdapter() {
      @Override
      public void windowClosing(final java.awt.event.WindowEvent evt) {
        exitFormWindowClosing(evt);
      }
    });

    emulatorsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    emulatorsPanel.setLayout(new java.awt.BorderLayout());

    mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Clear which link?"));
    mainPanel.setLayout(new java.awt.GridLayout(3, 1));

    buttonGroup1.add(prequel);
    prequel.setMnemonic('P');
    prequel.setText("Precursor");
    prequel.addActionListener(new java.awt.event.ActionListener() {
      @Override
      public void actionPerformed(final java.awt.event.ActionEvent evt) {
        linkTypeChanged_ActionPerformed(evt);
      }
    });
    mainPanel.add(prequel);

    buttonGroup1.add(sequel);
    sequel.setMnemonic('S');
    sequel.setText("Sequel");
    sequel.addActionListener(new java.awt.event.ActionListener() {
      @Override
      public void actionPerformed(final java.awt.event.ActionEvent evt) {
        linkTypeChanged_ActionPerformed(evt);
      }
    });
    mainPanel.add(sequel);

    buttonGroup1.add(related);
    related.setMnemonic('R');
    related.setText("Related Game");
    related.addActionListener(new java.awt.event.ActionListener() {
      @Override
      public void actionPerformed(final java.awt.event.ActionEvent evt) {
        linkTypeChanged_ActionPerformed(evt);
      }
    });
    mainPanel.add(related);

    emulatorsPanel.add(mainPanel, java.awt.BorderLayout.CENTER);

    getContentPane().add(emulatorsPanel, java.awt.BorderLayout.CENTER);

    OkCancelPanel.setLayout(new java.awt.BorderLayout());

    jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    okButton.setMnemonic('O');
    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      @Override
      public void actionPerformed(final java.awt.event.ActionEvent evt) {
        okActionPerformed(evt);
      }
    });
    jPanel9.add(okButton);

    cancelButton.setMnemonic('C');
    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      @Override
      public void actionPerformed(final java.awt.event.ActionEvent evt) {
        cancelActionPerformed(evt);
      }
    });
    jPanel9.add(cancelButton);

    OkCancelPanel.add(jPanel9, java.awt.BorderLayout.EAST);

    bidirectionalLink.setMnemonic('M');
    bidirectionalLink.setText("Clear bidirectional Link");
    OkCancelPanel.add(bidirectionalLink, java.awt.BorderLayout.WEST);

    getContentPane().add(OkCancelPanel, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void linkTypeChanged_ActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_linkTypeChanged_ActionPerformed
    linkTypeChanged();
  }// GEN-LAST:event_linkTypeChanged_ActionPerformed

  private void linkTypeChanged() {
    linkGame = null;
    bidirectionalLink.setSelected(false);

    if (prequel.isSelected() && game.hasPrequel()) {
      linkGame = Db.getGameById(game.getPrequelId());
      bidirectionalLink.setEnabled(linkGame.getSequelId() == game.getId());
    } else if (sequel.isSelected() && game.hasSequel()) {
      linkGame = Db.getGameById(game.getSequelId());
      bidirectionalLink.setEnabled(linkGame.getPrequelId() == game.getId());
    } else if (game.hasRelated()) {
      linkGame = Db.getGameById(game.getRelatedId());
      bidirectionalLink.setEnabled(linkGame.getRelatedId() == game.getId());
    }

  }

  private void cancelActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelActionPerformed
    dispose();
  }// GEN-LAST:event_cancelActionPerformed

  private void okActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okActionPerformed

    if (prequel.isSelected()) {
      game.setPrequelId(0);
      if (bidirectionalLink.isSelected() && (linkGame != null)) {
        linkGame.setSequelId(0);
      }
    } else if (sequel.isSelected()) {
      game.setSequelId(0);
      if (bidirectionalLink.isSelected() && (linkGame != null)) {
        linkGame.setPrequelId(0);
      }
    } else {
      game.setRelatedId(0);
      if (bidirectionalLink.isSelected() && (linkGame != null)) {
        linkGame.setRelatedId(0);
      }
    }

    dispose();

    Db.saveOrUpdate(game);
    if (linkGame != null) {
      Db.saveOrUpdate(linkGame);
    }

  }// GEN-LAST:event_okActionPerformed

  private void exitFormWindowClosing(final java.awt.event.WindowEvent evt) {// GEN-FIRST:event_exitFormWindowClosing
    dispose();
  }// GEN-LAST:event_exitFormWindowClosing
}