.TH jGameBase 6
.SH NAME
jGameBase \- retro-gaming emulator frontend.

.SH SYNOPSIS
.B jgamebase
[-help] [-usage] [toolbox]

.SH DESCRIPTION
A fully-featured retro-gaming emulator frontend and game database utility. It is a sister application to the Windows(TM) program GameBase (without "j"), the official frontend for the Gamebase64 Collection. It supports virtually any emulator for any system and has versatile database searching and filtering. There are databases for Apple II, Atari ST, Coleco ColecoVision, Commodore Amiga, Commodore C64, Commodore VIC20, Nintendo NES, Nintendo SNES, Sinclair ZXSpectrum, and other systems. 

.TP
\-help
Display help on homepage, contact, and license.

.TP
\-usage
Display usage message.

.TP
toolbox
Start the database toolbox.
.P
For more information please browse the program documentation in
.IR /usr/share/doc/jgamebase
or the homepage at
.IR <http://jgamebase.sourceforge.net/> .
 
.SH ENVIRONMENT
jGameBase is written in Java(TM) and needs a JRE (Java Runtime Environment) greater or equal to Java 1.6 to run.

.SH AUTHOR
Written by Frank Gerbig <fgerbig@sourceforge.net>, GameBase written by James Burrows.

.SH COPYRIGHT
Copyright © 2006-2011 Frank Gerbig.  License GPLv3: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
